# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user1', models.CharField(default='', max_length=255)),
                ('user2', models.CharField(default='', max_length=255)),
                ('info', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('tokenId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tokenTime', models.DateTimeField(auto_now=True)),
                ('roomId', models.CharField(default='', max_length=255)),
                ('matchState', models.IntegerField(default=0)),
                ('tokenText', models.TextField(default='')),
            ],
        ),
    ]
