# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeGame', '0002_auto_20161203_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turnCount',
            field=models.IntegerField(default=0),
        ),
    ]
